### ISSUE TITLE
Questions about this repository

### ISSUE THREAD

**Issue by Wuzzy2** [Soldat/prebuilt-libs#1]
I have a few questions about this repository.

What exactly is this repository? And why is it required in the installation process? Could it maybe be avoided on Linux, at least in theory (for example, if the user already has these libraries installed system-wide)?

Can you please clarify which libraries you're using?

PhysFS is obvious, no question here.
But libGameNetworkingSockets is this one, right?: https://github.com/ValveSoftware/GameNetworkingSockets
And libstb is this one, right?: https://github.com/wbuntine/libstb

**Comment by Wuzzy2** [comment]
Another question: Which versions of the libraries did you use to build the pre-built libraries?

In other words: Which versions of the libraries do I need to build Soldat?

**Comment by zenyd** [comment]
I'm not too sure how these libraries were built, but I can say with certainty that they are not strictly required. libstb for example is included in the source code (were you can build it yourself). GameNetworkingSockets you most likely have to build from source. Even if you're distribution has the package it may not be compatible with the version used in soldat. I built it from commit 8f60b0e6bf50b44d5cc6587b8ddcccc4d2a8e78c. Recent changes in the library broke compatibility with soldat.

Some of the library versions needed are listed in the dependencies in the soldat repo. I'd just try to use the most recent versions of the libraries and if that doesn't work build the correct version from source.

**Comment by Wuzzy2** [comment]
Thanks! This answers my questions.

**Comment by Thann** [comment]
If this project relies on a specific commit of GNS, would it be possible to submodule it in?
